# Use package name as site title
title: "MCP Ruby SDK"
description: "The official Ruby SDK for Model Context Protocol servers and clients."
remote_theme: just-the-docs/just-the-docs

# Include generated files and directories which may start with underscores
include:
  - "_*"

# Search
search_enabled: true

# Footer
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/modelcontextprotocol/ruby-sdk"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"
